### ISSUE TITLE
Document authorship and license

### ISSUE THREAD

**Issue by LevanBokeria** [AMI-system/gbif_download_standalone#19]
[Per suggestion here](https://softwareengineering.stackexchange.com/questions/386582/altering-author-names-in-mit-license) I am copying over the [LICENSE](https://github.com/RolnickLab/gbif-species-trainer/blob/master/LICENSE) file from the Rolnick lab repository, and adding my name and @KatrionaGoldmann's name. 

@ots22 should we add an institutional name too, like they've done for the Rolnick lab? Or just our names are enough?

**Comment by KatrionaGoldmann** [comment]
Licenses added for [gbif_download_standalone](https://github.com/AMI-system/gbif_download_standalone),  [species_classifier](https://github.com/AMI-system/species_classifier), [pi_inferences](https://github.com/AMI-system/pi_inferences), and [ami_setup](https://github.com/AMI-system/ami_setup).
